#!/usr/bin/env python

"""C include file style hexdump creator

Project home: https://github.com/puuu/MQTT433gateway/
"""

from textwrap import wrap

TEMPLATE = """
// DO NOT EDIT
//
// This file is autogenerated!
const unsigned long {var_name}_len = {length};
const char PROGMEM {var_name}[] = {{
  {hexdump}
}};
"""

def dump(infile_name, outfile_name, var_name=None):
    with open(infile_name, "rb") as infile:
        if var_name is None:
            var_name = infile_name.replace('/', '_').replace('\\', '_').replace('.', '_')
        contents = infile.read()
        hexdump = ", ".join(['0x{:02x}'.format(ch) for ch in contents])
        formatted = "\n  ".join(wrap(hexdump, 72))
        with open(outfile_name, "w") as outfile:
            outfile.write(TEMPLATE.format(var_name=var_name,
                                          hexdump=formatted,
                                          length=len(contents)))
    return


def main():
    import sys
    infile = sys.argv[1]
    outfile = sys.argv[2]
    dump(infile, outfile)
    return


if __name__ == "__main__":
    main()
